steps:  
  - id: 'tf apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args: 
    - '-c'
    - | 
        echo "branch $BRANCH_NAME"
          cd modules-disks-wise/
          echo "#......Destruction Initiated...please be patient !......#"
          terraform destroy -auto-approve