steps:
  - id: 'tf apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args: 
    - '-c'
    - | 
          echo "-------------------------------------------------------------------------------------"
          echo "-------------------------------------------------------------------------------------"
          echo "branch $BRANCH_NAME"

          echo "-------------------------------------------------------------------------------------"
          echo "-------------------------------------------------------------------------------------"
          cd modules-disks-wise/
          echo "#........... Initiation in progress...please be patient !! .............#"
          terraform init


          echo "-------------------------------------------------------------------------------------"
          echo "-------------------------------------------------------------------------------------"
          echo "#............. Validation Initiated...please be patient !! .............#"
          terraform validate


          echo "-------------------------------------------------------------------------------------"
          echo "-------------------------------------------------------------------------------------"
          echo "#............... Plan Initiated...please be patient !! .................#"
          terraform plan -out terraform.plan


          echo "-------------------------------------------------------------------------------------"
          echo "-------------------------------------------------------------------------------------"
          echo "#.............. Build Initiated...please be patient !! .................#"
          terraform apply -auto-approve terraform.plan